In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('State_data.csv')
df.drop('Unnamed: 0',axis=1,inplace=True)
df

,index,districts,delta.tested,delta.vaccinated1,delta.vaccinated2,delta21_14.confirmed,delta7.confirmed,delta7.recovered,delta7.tested,delta7.vaccinated1,...,delta.confirmed,delta.deceased,delta.recovered,delta7.deceased,meta.notes,total.other,delta7.other,delta21_14,delta.other,meta.vaccinated.source
0,AN,Nicobars,1376.0,3.0,13.0,9.0,3.0,5.0,8936.0,884,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AN,North and Middle Andaman,1376.0,3.0,13.0,9.0,3.0,5.0,8936.0,884,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AN,South Andaman,1376.0,3.0,13.0,9.0,3.0,5.0,8936.0,884,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AN,Unknown,1376.0,3.0,13.0,9.0,3.0,5.0,8936.0,884,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AP,Anantapur,39848.0,20497.0,24137.0,3220.0,2873.0,3590.0,254532.0,1223010,...,385.0,4.0,675.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744,WB,Purba Bardhaman,47417.0,209609.0,58881.0,4193.0,6453.0,5953.0,300114.0,3809597,...,914.0,15.0,913.0,86.0,NaN,NaN,NaN,NaN,NaN,NaN
745,WB,Purba Medinipur,47417.0,209609.0,58881.0,4193.0,6453.0,5953.0,300114.0,3809597,...,914.0,15.0,913.0,86.0,NaN,NaN,NaN,NaN,NaN,NaN
746,WB,Purulia,47417.0,209609.0,58881.0,4193.0,6453.0,5953.0,300114.0,3809597,...,914.0,15.0,913.0,86.0,NaN,NaN,NaN,NaN,NaN,NaN
747,WB,South 24 Parganas,47417.0,209609.0,58881.0,4193.0,6453.0,5953.0,300114.0,3809597,...,914.0,15.0,913.0,86.0,NaN,NaN,NaN,NaN,NaN,NaN
748,WB,Uttar Dinajpur,47417.0,209609.0,58881.0,4193.0,6453.0,5953.0,300114.0,3809597,...,914.0,15.0,913.0,86.0,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.rename(columns = {'index':'State'}, inplace = True)

In [4]:
df

,State,districts,delta.tested,delta.vaccinated1,delta.vaccinated2,delta21_14.confirmed,delta7.confirmed,delta7.recovered,delta7.tested,delta7.vaccinated1,...,delta.confirmed,delta.deceased,delta.recovered,delta7.deceased,meta.notes,total.other,delta7.other,delta21_14,delta.other,meta.vaccinated.source
0,AN,Nicobars,1376.0,3.0,13.0,9.0,3.0,5.0,8936.0,884,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AN,North and Middle Andaman,1376.0,3.0,13.0,9.0,3.0,5.0,8936.0,884,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AN,South Andaman,1376.0,3.0,13.0,9.0,3.0,5.0,8936.0,884,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AN,Unknown,1376.0,3.0,13.0,9.0,3.0,5.0,8936.0,884,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AP,Anantapur,39848.0,20497.0,24137.0,3220.0,2873.0,3590.0,254532.0,1223010,...,385.0,4.0,675.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744,WB,Purba Bardhaman,47417.0,209609.0,58881.0,4193.0,6453.0,5953.0,300114.0,3809597,...,914.0,15.0,913.0,86.0,NaN,NaN,NaN,NaN,NaN,NaN
745,WB,Purba Medinipur,47417.0,209609.0,58881.0,4193.0,6453.0,5953.0,300114.0,3809597,...,914.0,15.0,913.0,86.0,NaN,NaN,NaN,NaN,NaN,NaN
746,WB,Purulia,47417.0,209609.0,58881.0,4193.0,6453.0,5953.0,300114.0,3809597,...,914.0,15.0,913.0,86.0,NaN,NaN,NaN,NaN,NaN,NaN
747,WB,South 24 Parganas,47417.0,209609.0,58881.0,4193.0,6453.0,5953.0,300114.0,3809597,...,914.0,15.0,913.0,86.0,NaN,NaN,NaN,NaN,NaN,NaN
748,WB,Uttar Dinajpur,47417.0,209609.0,58881.0,4193.0,6453.0,5953.0,300114.0,3809597,...,914.0,15.0,913.0,86.0,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.drop('districts',axis=1,inplace=True)

In [6]:
df

,State,delta.tested,delta.vaccinated1,delta.vaccinated2,delta21_14.confirmed,delta7.confirmed,delta7.recovered,delta7.tested,delta7.vaccinated1,delta7.vaccinated2,...,delta.confirmed,delta.deceased,delta.recovered,delta7.deceased,meta.notes,total.other,delta7.other,delta21_14,delta.other,meta.vaccinated.source
0,AN,1376.0,3.0,13.0,9.0,3.0,5.0,8936.0,884,10640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AN,1376.0,3.0,13.0,9.0,3.0,5.0,8936.0,884,10640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AN,1376.0,3.0,13.0,9.0,3.0,5.0,8936.0,884,10640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AN,1376.0,3.0,13.0,9.0,3.0,5.0,8936.0,884,10640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AP,39848.0,20497.0,24137.0,3220.0,2873.0,3590.0,254532.0,1223010,1887005,...,385.0,4.0,675.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744,WB,47417.0,209609.0,58881.0,4193.0,6453.0,5953.0,300114.0,3809597,1871612,...,914.0,15.0,913.0,86.0,NaN,NaN,NaN,NaN,NaN,NaN
745,WB,47417.0,209609.0,58881.0,4193.0,6453.0,5953.0,300114.0,3809597,1871612,...,914.0,15.0,913.0,86.0,NaN,NaN,NaN,NaN,NaN,NaN
746,WB,47417.0,209609.0,58881.0,4193.0,6453.0,5953.0,300114.0,3809597,1871612,...,914.0,15.0,913.0,86.0,NaN,NaN,NaN,NaN,NaN,NaN
747,WB,47417.0,209609.0,58881.0,4193.0,6453.0,5953.0,300114.0,3809597,1871612,...,914.0,15.0,913.0,86.0,NaN,NaN,NaN,NaN,NaN,NaN
748,WB,47417.0,209609.0,58881.0,4193.0,6453.0,5953.0,300114.0,3809597,1871612,...,914.0,15.0,913.0,86.0,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df = df.drop_duplicates()
df

,State,delta.tested,delta.vaccinated1,delta.vaccinated2,delta21_14.confirmed,delta7.confirmed,delta7.recovered,delta7.tested,delta7.vaccinated1,delta7.vaccinated2,...,delta.confirmed,delta.deceased,delta.recovered,delta7.deceased,meta.notes,total.other,delta7.other,delta21_14,delta.other,meta.vaccinated.source
0,AN,1376.0,3.0,13.0,9.0,3.0,5.0,8936.0,884,10640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AP,39848.0,20497.0,24137.0,3220.0,2873.0,3590.0,254532.0,1223010,1887005,...,385.0,4.0,675.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN
19,AR,334.0,42.0,195.0,87.0,66.0,97.0,4788.0,3312,23647,...,1.0,NaN,9.0,NaN,[July 25]: All numbers corresponding to Papum ...,NaN,NaN,NaN,NaN,NaN
45,AS,15060.0,19124.0,37463.0,1499.0,2056.0,2215.0,269097.0,274869,849889,...,212.0,1.0,236.0,24.0,[Jan 1]: 1347 cases i.e Covid +'tive patients ...,1347.0,NaN,NaN,NaN,NaN
79,BR,226443.0,114694.0,145827.0,30.0,40.0,31.0,1378539.0,1286708,2144970,...,8.0,NaN,9.0,NaN,[June 9] : 3951 deceased cases have been repor...,1.0,NaN,NaN,NaN,NaN
117,CH,1403.0,211.0,1282.0,23.0,28.0,20.0,10726.0,3680,21641,...,5.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,CT,11869.0,21312.0,39393.0,124.0,205.0,103.0,147451.0,379374,604260,...,32.0,1.0,32.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN
147,DL,56751.0,12482.0,11839.0,195.0,267.0,239.0,395086.0,160323,269146,...,45.0,NaN,46.0,NaN,[July 14]: Value for the total tests conducted...,NaN,NaN,NaN,NaN,NaN
148,DN,NaN,3.0,20.0,4.0,NaN,2.0,NaN,2802,14244,...,NaN,NaN,1.0,NaN,NaN,31.0,NaN,NaN,NaN,NaN
151,GA,2361.0,2572.0,12404.0,409.0,222.0,409.0,19026.0,8418,46494,...,23.0,NaN,53.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN
154,GJ,34282.0,14685.0,62096.0,149.0,159.0,116.0,328489.0,335172,1660382,...,20.0,NaN,23.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
188,HP,3613.0,371.0,8192.0,958.0,1537.0,1154.0,64352.0,13244,234011,...,85.0,1.0,198.0,20.0,NaN,16.0,-1.0,NaN,NaN,NaN
200,HR,20588.0,7867.0,15801.0,83.0,95.0,87.0,148110.0,160777,368141,...,11.0,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222,JH,31238.0,41034.0,51488.0,78.0,137.0,250.0,464579.0,299587,428313,...,10.0,NaN,8.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN
247,JK,38915.0,1584.0,45202.0,529.0,611.0,572.0,254608.0,33383,414843,...,95.0,NaN,79.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN
267,KA,106939.0,17604.0,28163.0,2432.0,2347.0,2339.0,724215.0,623591,1373861,...,292.0,11.0,345.0,75.0,NaN,29.0,NaN,NaN,NaN,NaN
298,KL,65158.0,2010.0,11914.0,59521.0,53326.0,48406.0,506604.0,109805,792534,...,7167.0,167.0,6439.0,3089.0,NaN,529.0,NaN,NaN,NaN,NaN
312,LA,388.0,NaN,2.0,26.0,58.0,28.0,2475.0,525,1532,...,11.0,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,LD,31.0,NaN,4.0,NaN,NaN,NaN,1625.0,69,796,...,NaN,NaN,NaN,NaN,NaN,44.0,NaN,NaN,NaN,NaN
315,MH,108040.0,53161.0,31988.0,13825.0,8117.0,15146.0,773516.0,1611778,1282938,...,1172.0,20.0,1399.0,200.0,"[Dec 16]:10,218 duplicate cases & other state ...",3619.0,7.0,NaN,NaN,NaN
351,ML,1559.0,38.0,203.0,530.0,256.0,460.0,13944.0,7871,41927,...,22.0,1.0,51.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN
362,MN,1689.0,705.0,4283.0,734.0,439.0,652.0,12787.0,7665,71276,...,63.0,1.0,62.0,10.0,[Dec 14]:824 out of 980 recovered cases are ba...,NaN,NaN,NaN,NaN,NaN
379,MP,55368.0,5713.0,77062.0,63.0,105.0,74.0,393209.0,148817,2034460,...,16.0,NaN,8.0,1.0,[14 Oct'20]: 4469 confirmed cases and 4469 rec...,NaN,NaN,NaN,NaN,NaN
433,MZ,5945.0,10.0,51.0,6770.0,4098.0,5685.0,42841.0,4302,11262,...,579.0,2.0,610.0,21.0,NaN,NaN,NaN,NaN,NaN,NaN
444,NL,468.0,193.0,822.0,162.0,130.0,144.0,4606.0,4706,23628,...,11.0,1.0,21.0,6.0,NaN,1043.0,13.0,NaN,1.0,NaN
455,OR,69675.0,21420.0,25651.0,3381.0,3046.0,3230.0,473919.0,731837,917236,...,488.0,4.0,450.0,24.0,[July 12th] :20 non-covid deaths reported in s...,NaN,NaN,NaN,NaN,NaN
486,PB,34152.0,3321.0,4418.0,159.0,192.0,162.0,221114.0,200182,223256,...,26.0,1.0,25.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN
508,PY,2662.0,171.0,532.0,343.0,278.0,315.0,21095.0,8324,20073,...,38.0,NaN,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
512,RJ,13454.0,9399.0,29672.0,31.0,27.0,26.0,95132.0,271500,864947,...,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
549,SK,389.0,NaN,NaN,82.0,79.0,76.0,2847.0,782,14044,...,21.0,1.0,8.0,2.0,NaN,325.0,6.0,NaN,NaN,NaN
554,TG,25021.0,38781.0,26738.0,1068.0,1189.0,1121.0,261086.0,1072389,961422,...,121.0,1.0,183.0,9.0,[July 27] : Telangana bulletin for the previou...,NaN,NaN,NaN,NaN,NaN
588,TN,123701.0,77325.0,106584.0,8827.0,7407.0,8852.0,858304.0,788134,1578082,...,1009.0,19.0,1183.0,97.0,[June 29 2021]: TN has introduced a new distri...,NaN,NaN,NaN,NaN,NaN
628,TR,3501.0,3.0,650.0,49.0,87.0,62.0,22126.0,4155,74642,...,12.0,NaN,2.0,NaN,[Aug 4]: Tripura bulletin for the previous day...,63.0,NaN,NaN,NaN,NaN
636,TT,881379.0,750410.0,933460.0,109755.0,96071.0,101753.0,8431577.0,15883780,24527530,...,12907.0,251.0,13152.0,3727.0,NaN,13197.0,37.0,NaN,1.0,https://www.pib.gov.in/PressReleasePage.aspx?P...
637,UP,161458.0,53401.0,57556.0,74.0,63.0,58.0,1140736.0,2266921,3130828,...,6.0,NaN,6.0,1.0,[Jan 1]:As no bulletin was provided for 31'st ...,NaN,NaN,NaN,NaN,NaN
712,UT,9524.0,1065.0,12934.0,88.0,75.0,74.0,83377.0,25250,258381,...,5.0,NaN,9.0,1.0,[Oct 30]: Metric of capturing the testing data...,6150.0,12.0,NaN,NaN,NaN
725,WB,47417.0,209609.0,58881.0,4193.0,6453.0,5953.0,300114.0,3809597,1871612,...,914.0,15.0,913.0,86.0,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df = df.reset_index()

In [9]:
df.drop('index',axis=1,inplace=True)

In [10]:
df.columns

Index(['State', 'delta.tested', 'delta.vaccinated1', 'delta.vaccinated2',
       'delta21_14.confirmed', 'delta7.confirmed', 'delta7.recovered',
       'delta7.tested', 'delta7.vaccinated1', 'delta7.vaccinated2',
       'meta.date', 'meta.last_updated', 'meta.population', 'meta.tested.date',
       'meta.tested.source', 'meta.vaccinated.date', 'total.confirmed',
       'total.deceased', 'total.recovered', 'total.tested',
       'total.vaccinated1', 'total.vaccinated2', 'delta.confirmed',
       'delta.deceased', 'delta.recovered', 'delta7.deceased', 'meta.notes',
       'total.other', 'delta7.other', 'delta21_14', 'delta.other',
       'meta.vaccinated.source'],
      dtype='object')

In [11]:
df.drop(['meta.notes','meta.vaccinated.source','meta.tested.source','meta.last_updated'],axis=1,inplace=True)

In [12]:
df = df.fillna(0)

In [13]:
pd.set_option('display.max_columns', None)
df.head()

,State,delta.tested,delta.vaccinated1,delta.vaccinated2,delta21_14.confirmed,delta7.confirmed,delta7.recovered,delta7.tested,delta7.vaccinated1,delta7.vaccinated2,meta.date,meta.population,meta.tested.date,meta.vaccinated.date,total.confirmed,total.deceased,total.recovered,total.tested,total.vaccinated1,total.vaccinated2,delta.confirmed,delta.deceased,delta.recovered,delta7.deceased,total.other,delta7.other,delta21_14,delta.other
0,AN,1376.0,3.0,13.0,9.0,3.0,5.0,8936.0,884,10640,2021-10-31,397000,2021-10-31,2021-10-31,7651,129,7518,598033,294001,200157,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,AP,39848.0,20497.0,24137.0,3220.0,2873.0,3590.0,254532.0,1223010,1887005,2021-10-31,52221000,2021-10-31,2021-10-31,2066450,14373,2047722,29518787,32976969,20375181,385.0,4.0,675.0,30.0,0.0,0.0,0.0,0.0
2,AR,334.0,42.0,195.0,87.0,66.0,97.0,4788.0,3312,23647,2021-10-31,1504000,2021-10-31,2021-10-31,55155,280,54774,1185436,771875,534486,1.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0
3,AS,15060.0,19124.0,37463.0,1499.0,2056.0,2215.0,269097.0,274869,849889,2021-10-31,34293000,2021-10-31,2021-10-31,610645,5997,600974,24712042,20172463,8068795,212.0,1.0,236.0,24.0,1347.0,0.0,0.0,0.0
4,BR,226443.0,114694.0,145827.0,30.0,40.0,31.0,1378539.0,1286708,2144970,2021-10-31,119520000,2021-10-31,2021-10-31,726098,9661,716390,50531824,49874828,18346781,8.0,0.0,9.0,0.0,1.0,0.0,0.0,0.0

In [14]:
df.isnull().sum()

State                   0
delta.tested            0
delta.vaccinated1       0
delta.vaccinated2       0
delta21_14.confirmed    0
delta7.confirmed        0
delta7.recovered        0
delta7.tested           0
delta7.vaccinated1      0
delta7.vaccinated2      0
meta.date               0
meta.population         0
meta.tested.date        0
meta.vaccinated.date    0
total.confirmed         0
total.deceased          0
total.recovered         0
total.tested            0
total.vaccinated1       0
total.vaccinated2       0
delta.confirmed         0
delta.deceased          0
delta.recovered         0
delta7.deceased         0
total.other             0
delta7.other            0
delta21_14              0
delta.other             0
dtype: int64

In [15]:
df.dtypes

State                    object
delta.tested            float64
delta.vaccinated1       float64
delta.vaccinated2       float64
delta21_14.confirmed    float64
delta7.confirmed        float64
delta7.recovered        float64
delta7.tested           float64
delta7.vaccinated1        int64
delta7.vaccinated2        int64
meta.date                object
meta.population           int64
meta.tested.date         object
meta.vaccinated.date     object
total.confirmed           int64
total.deceased            int64
total.recovered           int64
total.tested              int64
total.vaccinated1         int64
total.vaccinated2         int64
delta.confirmed         float64
delta.deceased          float64
delta.recovered         float64
delta7.deceased         float64
total.other             float64
delta7.other            float64
delta21_14              float64
delta.other             float64
dtype: object

In [16]:
df.to_csv('Cleaned_State_wise.csv',index=False)

In [20]:
dd = pd.read_csv('district_wise_data.csv')
# dd.drop('Unnamed: 0',axis=1,inplace=True)
dd

,State,District,2.delta7.vaccinated1,2.delta7.vaccinated2,2.meta.population,2.total.vaccinated1,2.total.vaccinated2,2.delta.vaccinated2,2.delta.vaccinated1,2.delta21_14.confirmed,2.delta7.confirmed,2.delta7.recovered,2.total.confirmed,2.total.deceased,2.total.recovered,2.delta.confirmed,2.delta.recovered,2.meta.tested.date,2.total.tested,2.delta.deceased,2.delta7.deceased,2.total.other,2.delta.tested,2.delta7.tested,2.meta.tested.source,2.meta.vaccinated.date,2.delta7.other,2.meta.notes,2.delta.other
0,AN,Nicobars,62.0,811.0,36842.0,25394.0,20313.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0,0.0
1,AN,North and Middle Andaman,90.0,1839.0,105597.0,78945.0,59522.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0,0.0
2,AN,South Andaman,732.0,8012.0,238142.0,189662.0,120322.0,28.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0,0.0
3,AN,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,3.0,5.0,7651.0,129.0,7518.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0,0.0
4,AP,Anantapur,92803.0,140903.0,4083315.0,2690082.0,1611476.0,5370.0,4575.0,50.0,38.0,58.0,157843.0,1093.0,156699.0,4.0,5.0,2020-11-26,787085.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,TR,North Tripura,352.0,4099.0,415946.0,283802.0,190594.0,0.0,0.0,8.0,4.0,8.0,7250.0,34.0,7199.0,2.0,0.0,2021-02-02,100931.0,0.0,0.0,7.0,0.0,0.0,0,0,0.0,0,0.0
632,TR,Sipahijala,451.0,10397.0,484233.0,330932.0,211903.0,9.0,0.0,2.0,8.0,4.0,6360.0,75.0,6273.0,0.0,0.0,2021-02-02,53067.0,0.0,0.0,1.0,0.0,0.0,0,0,0.0,0,0.0
633,TR,South Tripura,267.0,5639.0,433737.0,303987.0,209259.0,1.0,0.0,1.0,4.0,1.0,10168.0,53.0,10104.0,1.0,0.0,2021-02-02,83030.0,0.0,0.0,3.0,0.0,0.0,0,0,0.0,0,0.0
634,TR,Unokoti,762.0,10307.0,277335.0,173390.0,101178.0,5.0,0.0,1.0,4.0,3.0,8609.0,68.0,8530.0,1.0,0.0,2021-02-02,34930.0,0.0,0.0,4.0,0.0,0.0,0,0,0.0,0,0.0
635,TR,West Tripura,1366.0,17141.0,917534.0,676784.0,470030.0,13.0,5.0,33.0,55.0,41.0,32351.0,420.0,31817.0,6.0,2.0,2021-02-02,202939.0,0.0,0.0,43.0,0.0,0.0,0,0,0.0,0,0.0

In [23]:
for i in dd.columns:
    print(i)

State
District
2.delta7.vaccinated1
2.delta7.vaccinated2
2.meta.population
2.total.vaccinated1
2.total.vaccinated2
2.delta.vaccinated2
2.delta.vaccinated1
2.delta21_14.confirmed
2.delta7.confirmed
2.delta7.recovered
2.total.confirmed
2.total.deceased
2.total.recovered
2.delta.confirmed
2.delta.recovered
2.meta.tested.date
2.total.tested
2.delta.deceased
2.delta7.deceased
2.total.other
2.delta.tested
2.delta7.tested
2.meta.vaccinated.date
2.delta7.other
2.delta.other

In [21]:
dd.drop(['2.meta.notes','2.meta.tested.source'],axis=1,inplace=True)

In [22]:
dd.head()

,State,District,2.delta7.vaccinated1,2.delta7.vaccinated2,2.meta.population,2.total.vaccinated1,2.total.vaccinated2,2.delta.vaccinated2,2.delta.vaccinated1,2.delta21_14.confirmed,2.delta7.confirmed,2.delta7.recovered,2.total.confirmed,2.total.deceased,2.total.recovered,2.delta.confirmed,2.delta.recovered,2.meta.tested.date,2.total.tested,2.delta.deceased,2.delta7.deceased,2.total.other,2.delta.tested,2.delta7.tested,2.meta.vaccinated.date,2.delta7.other,2.delta.other
0,AN,Nicobars,62.0,811.0,36842.0,25394.0,20313.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0
1,AN,North and Middle Andaman,90.0,1839.0,105597.0,78945.0,59522.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0
2,AN,South Andaman,732.0,8012.0,238142.0,189662.0,120322.0,28.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0
3,AN,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,3.0,5.0,7651.0,129.0,7518.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0
4,AP,Anantapur,92803.0,140903.0,4083315.0,2690082.0,1611476.0,5370.0,4575.0,50.0,38.0,58.0,157843.0,1093.0,156699.0,4.0,5.0,2020-11-26,787085.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0

In [25]:
dd['2.meta.tested.date']= pd.to_datetime(dd['2.meta.tested.date'], errors='coerce')
dd['2.meta.vaccinated.date']= pd.to_datetime(dd['2.meta.vaccinated.date'], errors='coerce')

In [26]:
dd.head()

,State,District,2.delta7.vaccinated1,2.delta7.vaccinated2,2.meta.population,2.total.vaccinated1,2.total.vaccinated2,2.delta.vaccinated2,2.delta.vaccinated1,2.delta21_14.confirmed,2.delta7.confirmed,2.delta7.recovered,2.total.confirmed,2.total.deceased,2.total.recovered,2.delta.confirmed,2.delta.recovered,2.meta.tested.date,2.total.tested,2.delta.deceased,2.delta7.deceased,2.total.other,2.delta.tested,2.delta7.tested,2.meta.vaccinated.date,2.delta7.other,2.delta.other
0,AN,Nicobars,62.0,811.0,36842.0,25394.0,20313.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaT,0.0,0.0,0.0,0.0,0.0,0.0,NaT,0.0,0.0
1,AN,North and Middle Andaman,90.0,1839.0,105597.0,78945.0,59522.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaT,0.0,0.0,0.0,0.0,0.0,0.0,NaT,0.0,0.0
2,AN,South Andaman,732.0,8012.0,238142.0,189662.0,120322.0,28.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaT,0.0,0.0,0.0,0.0,0.0,0.0,NaT,0.0,0.0
3,AN,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,3.0,5.0,7651.0,129.0,7518.0,0.0,0.0,NaT,0.0,0.0,0.0,0.0,0.0,0.0,NaT,0.0,0.0
4,AP,Anantapur,92803.0,140903.0,4083315.0,2690082.0,1611476.0,5370.0,4575.0,50.0,38.0,58.0,157843.0,1093.0,156699.0,4.0,5.0,2020-11-26,787085.0,0.0,0.0,0.0,0.0,0.0,NaT,0.0,0.0

In [27]:
dd=dd.fillna(0)

In [28]:
dd.to_csv('district_wise_data.csv')